ALTER TABLE retailers
ADD COLUMN street_address VARCHAR(255) DEFAULT '',
ADD COLUMN city VARCHAR(100) DEFAULT '',
ADD COLUMN state VARCHAR(100) DEFAULT '',
ADD COLUMN postal_code VARCHAR(20) DEFAULT '',
ADD COLUMN country VARCHAR(100) DEFAULT '';

ALTER TABLE wholesalers
ADD COLUMN street_address VARCHAR(255) DEFAULT '',
ADD COLUMN city VARCHAR(100) DEFAULT '',
ADD COLUMN state VARCHAR(100) DEFAULT '',
ADD COLUMN postal_code VARCHAR(20) DEFAULT '',
ADD COLUMN country VARCHAR(100) DEFAULT '';
